import org.gradle.api.tasks.Copy
import org.gradle.api.tasks.Exec
import java.io.File

plugins {
    kotlin("multiplatform")
}

// Источник ПДД: по умолчанию — папка pdd_russia-master из Downloads (можно задать -PpddSource=путь)
val pddSourceDir: java.io.File = if (project.hasProperty("pddSource")) {
    project.file(project.property("pddSource") as String)
} else {
    project.file("${System.getProperty("user.home")}/Downloads/pdd_russia-master/pdd_russia-master")
}

val copyPddToWeb = tasks.register<Copy>("copyPddToWeb") {
    into(layout.projectDirectory.dir("src/jsMain/resources/pdd"))
    if (pddSourceDir.exists()) {
        from(pddSourceDir) {
            include("questions/A_B/tickets/**")
            eachFile { path = path.replaceFirst("questions/A_B/tickets/", "tickets/") }
        }
        from(pddSourceDir) {
            include("questions/C_D/tickets/**")
            eachFile { path = path.replaceFirst("questions/C_D/tickets/", "tickets/C_D/") }
        }
        from(pddSourceDir) {
            include("images/**")
            eachFile { path = path.replaceFirst("images/", "images/") }
        }
        from(pddSourceDir) {
            include("markup/**")
            eachFile { path = path.replaceFirst("markup/", "markup/") }
        }
        from(pddSourceDir) {
            include("penalties/**")
            eachFile { path = path.replaceFirst("penalties/", "penalties/") }
        }
        from(pddSourceDir) {
            include("signs/**")
            eachFile { path = path.replaceFirst("signs/", "signs/") }
        }
    } else {
        from(project(":app").file("src/main/assets/pdd"))
    }
}

// Один JSON-бандл всех билетов (как на Android) — загружается одним запросом, без раздачи /pdd/tickets/
val buildPddBundle = tasks.register<Exec>("buildPddBundle") {
    dependsOn(copyPddToWeb)
    workingDir(projectDir)
    commandLine("node", "scripts/build-pdd-bundle.js")
}

// Встраиваем бандл в Kotlin-исходник, чтобы билеты работали без fetch и без pdd-tickets-bundle.js
val generatePddEmbedded = tasks.register<org.gradle.api.DefaultTask>("generatePddEmbedded") {
    dependsOn(buildPddBundle)
    val bundleJson = project.file("src/jsMain/resources/pdd-tickets-bundle.json")
    val outDir = layout.buildDirectory.dir("generated/pdd").get().asFile
    val outFile = File(outDir, "PddTicketsEmbedded.kt")
    outputs.file(outFile)
    outputs.upToDateWhen {
        bundleJson.exists() && outFile.exists() && outFile.lastModified() >= bundleJson.lastModified()
    }
    doLast {
        val json = bundleJson.readText(Charsets.UTF_8)
        val escaped = json.replace("\"\"\"", "\\\"\"\"")
        outDir.mkdirs()
        outFile.writeText(
            "// Generated by generatePddEmbedded — do not edit\n" +
            "object PddTicketsEmbedded {\n" +
            "    val json: String = \"\"\"$escaped\"\"\"\n" +
            "}\n",
            Charsets.UTF_8
        )
    }
}

// Копируем pdd в каталог, откуда dev-сервер раздаёт файлы (Working directory: build/js/packages/StartDrive-webApp)
val copyPddToDevOutput = tasks.register<Copy>("copyPddToDevOutput") {
    from(layout.buildDirectory.dir("processedResources/js/main/pdd"))
    into(rootProject.layout.buildDirectory.dir("js/packages/${rootProject.name}-${project.name}/pdd"))
}

kotlin {
    js(IR) {
        browser {
            runTask {
                devServerProperty.set(devServerProperty.get().copy(port = 8081, open = true))
            }
        }
        binaries.executable()
    }
    sourceSets {
        val jsMain by getting {
            kotlin.srcDir(layout.buildDirectory.dir("generated/pdd"))
            dependencies {
                implementation(project(":shared"))
                implementation(npm("firebase", "10.14.0"))
            }
        }
    }
}

tasks.named("jsProcessResources").configure { dependsOn(buildPddBundle) }
tasks.named("compileKotlinJs").configure { dependsOn(generatePddEmbedded) }
tasks.named("compileDevelopmentExecutableKotlinJs").configure { dependsOn(generatePddEmbedded) }
tasks.named("compileProductionExecutableKotlinJs").configure { dependsOn(generatePddEmbedded) }
tasks.named("jsBrowserDevelopmentRun").configure { dependsOn(copyPddToDevOutput) }
copyPddToDevOutput.configure {
    dependsOn(tasks.named("jsProcessResources"), tasks.named("jsDevelopmentExecutableCompileSync"))
    doFirst {
        val dest = rootProject.layout.buildDirectory.dir("js/packages/${rootProject.name}-${project.name}/pdd").get().asFile
        dest.mkdirs()
    }
}
